### ISSUE TITLE
BUG: yummy_load 

### ISSUE THREAD

**Issue by MASON-PRINCE** [Nikeshbajaj/MLEnd#1]
TrainSet, TestSet, MAPs = yummy_load(datadir_main = datadir,encode_labels=True)

This function generates the following bug when used：
   825         y2 = D_test['Diet'].to_numpy().copy()
    826 
--> 827         y_set = list(set(y1)|set(y2))
    828         y_set.sort()
    829 

TypeError: '<' not supported between instances of 'float' and 'str'

**Comment by Nikeshbajaj** [comment]
Thanks @MASON-PRINCE to point out. Bug s fixed now.

If you run following code with same ```subset``` and  ```save_to location``` as your previous, it will only update MLEndYD_image_attributes_benchmark.csv file. 

```
datadir = download_yummy(save_to = '../MLEnd', subset = subset,verbose=1,overwrite=False)

```
Then ``` yummy_load(datadir_main = datadir,encode_labels=True)``` won't raise any error.

Alternately, you can manually replace your local filed by updated [MLEndYD_image_attributes_benchmark.csv](https://github.com/MLEndDatasets/Yummy/raw/main/MLEndYD_image_attributes_benchmark.csv)
